routes/backend.php
<?php

use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\BannernoticeController;
use App\Http\Controllers\Backend\CareercategoryController;
use App\Http\Controllers\Backend\CareerController;
use App\Http\Controllers\Backend\CareerpositionController;
use App\Http\Controllers\Backend\Contact\ContactedController;
use App\Http\Controllers\Backend\Contact\ReportinformationController;
use App\Http\Controllers\Backend\ContactusController;
use App\Http\Controllers\Backend\DepartmentController;
use App\Http\Controllers\Backend\DesignationController;
use App\Http\Controllers\Backend\GalleryController;
use App\Http\Controllers\Backend\ImportantlinkController;
use App\Http\Controllers\Backend\NewsController;
use App\Http\Controllers\Backend\NoticecategoryController;
use App\Http\Controllers\Backend\NoticeController;
use App\Http\Controllers\Backend\PopupnoticeController;
use App\Http\Controllers\Backend\RegulationcategoryController;
use App\Http\Controllers\Backend\RegulationController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingdepartmentController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingroleController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingstaffController;
use App\Http\Controllers\Backend\StaffController;
use App\Http\Controllers\Backend\TendercategoryController;
use App\Http\Controllers\Backend\TenderController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['middleware' => 'admin'], function () {
    Route::get('dashboard', function () {
        return view('dashboard.index');
    })->name('dashboard.index');
    Route::resource('admin-banner-notice', BannernoticeController::class);
    Route::resource('admin-banner', BannerController::class);
    Route::resource('admin-notice-category', NoticecategoryController::class);
    Route::resource('admin-notice', NoticeController::class);
    Route::resource('admin-news', NewsController::class);
    Route::resource('admin-tender-category', TendercategoryController::class);
    Route::resource('admin-tender', TenderController::class);
    Route::resource('admin-career-category', CareercategoryController::class);
    Route::resource('admin-career-position', CareerpositionController::class);
    Route::resource('admin-career', CareerController::class);
    Route::resource('admin-designation', DesignationController::class);
    Route::resource('admin-department', DepartmentController::class);
    Route::resource('admin-staff', StaffController::class);
    Route::resource('admin-gallery', GalleryController::class);
    Route::get('admin/galleries/image/remove/{galleryimage}', 'App\Http\Controllers\Backend\GalleryController@removeGalleryImage')->name('admin.galleryimage.remove');

    Route::resource('admin-important-link', ImportantlinkController::class);
    Route::resource('admin-contact-detail', ContactusController::class);
    Route::resource('admin-trainer', TrainingstaffController::class);
    Route::resource('admin-training-role', TrainingroleController::class);
    Route::resource('admin-training-department', TrainingdepartmentController::class);
    Route::resource('admin-regulation-category', RegulationcategoryController::class);
    Route::resource('admin-regulation', RegulationController::class);

    Route::resource('admin-pop-notice', PopupnoticeController::class);

    Route::resource('admin-contacted', ContactedController::class);
    Route::resource('admin-report-information', ReportinformationController::class);

    Route::get('settings', 'App\Http\Controllers\Backend\Configuration\ConfigurationController@getConfiguration')->name('settings');
    Route::post('settings', 'App\Http\Controllers\Backend\Configuration\ConfigurationController@postConfiguration')->name('settings.update');
    Route::get('admin-about-us', 'App\Http\Controllers\Backend\Configuration\AboutusController@getConfiguration')->name('admin-about-us');
    Route::post('admin-about-us', 'App\Http\Controllers\Backend\Configuration\AboutusController@postConfiguration')->name('admin-about-us.update');
});

Route::get('/admin/login', 'App\Http\Controllers\Admin\Auth\AdminloginController@adminLogin')->name('admin/login');
Route::post('/loginadmin', 'App\Http\Controllers\Admin\Auth\AdminloginController@postAdminLogin')->name('loginadmin');
Route::get('/adminlogout', 'App\Http\Controllers\Admin\Auth\AdminloginController@adminLogout')->name('adminlogout');

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', 'App\Http\Controllers\Frontend\Home\HomeController@index')->name('/');
Route::get('about-us', 'App\Http\Controllers\Frontend\AboutUs\AboutusController@index')->name('about-us');
Route::get('tender', 'App\Http\Controllers\Frontend\Tender\TenderController@index')->name('tender');
Route::get('career', 'App\Http\Controllers\Frontend\Career\CareerController@index')->name('career');
Route::get('notice', 'App\Http\Controllers\Frontend\Notice\NoticeController@index')->name('notice');
Route::get('contact-us', 'App\Http\Controllers\Frontend\ContactUs\ContactusController@index')->name('contact-us');

Route::post('contact-us/post', 'App\Http\Controllers\Frontend\ContactUs\ContactusController@postIndex')->name('contact-us.post');

Route::get('gallery', 'App\Http\Controllers\Frontend\Gallery\GalleryController@index')->name('gallery');

Route::get('report-information', 'App\Http\Controllers\Frontend\ReportInformation\ReportInformationController@index')->name('report-information');
Route::post('report-information/post', 'App\Http\Controllers\Frontend\ReportInformation\ReportInformationController@postIndex')->name('report-information.post');

Route::get('regulation', 'App\Http\Controllers\Frontend\Regulation\RegulationController@index')->name('regulation');
Route::get('news-detail/{slug}', 'App\Http\Controllers\Frontend\Home\HomeController@getNewsdetail')->name('news-detail');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Gallery/Gallery.php
<?php

namespace App\Models\Gallery;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use File;

class Gallery extends Model
{
    use HasFactory;
    protected $fillable=['title','title_np','description','description_np','slug','status'];

    public function galleryImages()
    {
        return $this->hasMany(GalleryImage::class, 'image_id');
    }

    public function deleteImage() {
        if(file_exists('Admin/files/Gallery/'.basename($this->image))){
            file::delete('Admin/files/Gallery/'.basename($this->image));
        }
    }

}

app/Http/Controllers/Backend/GalleryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Gallery\Gallery;
use App\Models\Gallery\GalleryImage;
use App\Services\GalleryService;
use Yajra\DataTables\DataTables;
use File;

class GalleryController extends Controller
{
    protected $galleryService;

    public function __construct(GalleryService $galleryService)
    {
        $this->galleryService = $galleryService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = Gallery::with('galleryImages')->latest()->get();

            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    $editUrl = route('admin-gallery.edit', $data->id);
                    $actionBtn = '<a title="Edit Gallery" href="' . $editUrl . '" class="btn btn-sm btn-primary mr-2"><i class="fas fa-edit"></i></a>';
                    $actionBtn .= '<a title="Delete Gallery" class="btn btn-sm btn-danger" onclick="handleDelete(' . $data->id . ')"><i class="fas fa-trash"></i></a>';
                    return $actionBtn;
                })
                ->addColumn('status', function ($data) {
                    return $data->status == '0' ? 'In-Active' : 'Active';
                })
                ->addColumn('view', function ($data) {
                    $viewButton = $data->galleryImages->count() > 0 ?
                        '<a class="link m-2" data-toggle="modal" data-target="#previewGalleryImages' . $data->id . '">View images</a>' :
                        'No images';
                    return $viewButton;
                })
                ->rawColumns(['action', 'status', 'view'])
                ->make(true);
        }

        $galleries = Gallery::with('galleryImages')->latest()->get();
        return view('dashboard.gallery.index', compact('galleries'));
    }



    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('dashboard.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $data['image'] = $request->file('image');

        $this->galleryService->store($data);

        return redirect()->route('admin-gallery.index')->with('success', 'Gallery created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = Gallery::findOrFail($id);
        return view('dashboard.gallery.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = $request->all();
        $data['image'] = $request->file('image');

        $this->galleryService->update($data, $id);

        return redirect()->route('admin-gallery.index')->with('success', 'Gallery updated successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $gallery = Gallery::where('id', $id)->firstOrFail();

        $destination = 'Admin/files/Gallery/' . $gallery->featured_image;
        if (file::exists($destination)) {
            file::delete($destination);
        }

        $gallery->deleteImage();
        foreach($gallery->galleryimages as $galleryimage) {
            $galleryimage->deleteImage();
            $galleryimage->delete();
        }
        $gallery->delete();
        return redirect()->back()->with('success','Deleted Successfully');
    }

    public function removeGalleryImage($id)
    {
        $galleryImage = GalleryImage::findOrFail($id);
        $galleryImage->deleteImage();
        $galleryImage->delete();
        return redirect()->back()->with('success', 'Deleted Successfully');
    }
}

app/Http/Controllers/Frontend/Gallery/GalleryController.php
<?php

namespace App\Http\Controllers\Frontend\Gallery;

use App\Http\Controllers\Controller;
use App\Models\Gallery\Gallery;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    public function index(){
        $galleries = Gallery::orderby('id', 'desc')->with('galleryImages')->get();
        return view('Frontend.Gallery.index', ['galleries' => $galleries]);
    }
}

app/Http/Controllers/Training/Dashboard/Home/HomeController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Home;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        return view('Training.dashboard.index');
    }
}

app/Http/Controllers/Training/Dashboard/Material/MaterialController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Material;

use App\Http\Controllers\Controller;
use App\Models\Training\Material\TrainingMaterial;
use App\Models\RolesAndPermission\TrainingDepartment;
use Illuminate\Http\Request;
use App\Services\GenericService;
use Yajra\DataTables\DataTables;

class MaterialController extends Controller
{
    protected $genericService;

    public function __construct(GenericService $genericService)
    {
        $this->genericService = $genericService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = TrainingMaterial::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    $actionBtn = '<a title="Edit About-Us" href="/training-material/' . $data->id . '/edit" class="btn btn-sm btn-primary mr-2"><i class="fas fa-edit"></i></a>';
                    $actionBtn .= '<a title="Delete About-Us" class="btn btn-sm btn-danger" onclick="handleDelete(' . $data->id . ')"><i class="fas fa-trash"></i></a>';
                    return $actionBtn;
                })
                ->addColumn('status', function ($data) {
                    return $data->status == '0' ? 'In-Active' : 'Active';
                })
                ->addColumn('image', function ($data) {
                    $imagePath = $data->image ? asset('Admin/files/TrainingMaterial/'.$data->image) : asset('default_image/profile.png');
                    return '<a href="'.$imagePath.'" width="50" height="50" target="__blank" />View</a>';
                })
                ->rawColumns(['action','image'])
                ->make(true);
        }
        return view('Training.Dashboard.material.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $category=TrainingDepartment::all();
        return view('Training.Dashboard.material.create',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $this->genericService->store(new TrainingMaterial, $request->only(['title','title_np','description','description_np','slug','status','category_id','type']), $request->file('image'), 'image', 'slug','type');
        toast('Data Stored!', 'success');
        return redirect()->route('training-material.index')->with('success', 'Data created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = TrainingMaterial::findOrFail($id);
        $category=TrainingDepartment::all();
        return view('Training.Dashboard.material.edit', compact('data','category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $result = $this->genericService->update(new TrainingMaterial, $request->only(['title','title_np','description','description_np','slug','status','category_id','type']), $id, $request->file('image'), 'image', 'title', 'Admin/files/Notice');

        if ($result) {
            toast('Data Updated!', 'success');
            return redirect()->route('training-material.index')->with('success', 'Data updated successfully.');
        } else {
            return redirect()->route('training-material.index')->with('error', 'Failed to update testimonial.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = TrainingMaterial::find($id);
        if (file_exists('Admin/files/TrainingMaterial/' . basename($data->image))) {
            unlink('Admin/files/TrainingMaterial/' . basename($data->image));
        }
        $data->delete();
        // Alert::success('Congrats', 'You\'ve Successfully Deleted Data');
        toast('Data Deleted!', 'success');
        return redirect()->route('training-material.index');
    }
}

resources/views/dashboard/gallery/create.blade.php
@extends('dashboard.layouts.app')
@push('css')
<link rel="stylesheet" href="{{ asset('backend/assets/summernote/summernote-bs4.min.css') }}">

@endpush
@section('content')
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Gallery</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Gallery</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{route('admin-gallery.store')}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">

                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">Full Title</label>
                                <div class="col-md-3">
                                    <input class="form-control" name="title" type="text" placeholder="Full Title" id="example-text-input">
                                </div>
                                <label for="example-search-input" class="col-md-2 col-form-label">पुरा शीर्षक</label>
                                <div class="col-md-3">
                                    <input class="form-control" name="title_np" type="text" placeholder="पुरा शीर्षक" id="nepali">
                                </div>
                            </div>

                            <div class="mb-3 row">
                                <label for="example-email-input" class="col-md-2 col-form-label">Description</label>
                                <div class="col-md-12">
                                    <textarea class="summernote form-control" name="description" id="description"></textarea>
                                </div>
                                <label for="example-email-input" class="col-md-2 col-form-label">विवरण</label>
                                <div class="col-md-12">
                                    <textarea class="summernote_two form-control" name="description_np" id="description_np"></textarea>
                                </div>
                            </div>

                            <div class="mb-3 row">
                                <label for="example-email-input" class="col-md-2 col-form-label">File</label>
                                <div class="col-md-3">
                                    <input class="form-control" name="image[]" type="file"  id="example-email-input" multiple>
                                </div>

                            </div>

                        </div>

                        <div class="card-body">
                            <div class="col-sm-6">
                                <div class="mt-4">
                                    <div>
                                        <div class="input-group">
                                            <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div> <!-- end col -->
        </div>
        <!-- end row -->

    </div> <!-- container-fluid -->
</div>
<!-- End Page-content -->
@endsection
@push('js')
<script src="https://unpkg.com/nepalify"></script>
<script>
    nepalify.interceptElementById("nepali");
</script>
<!-- jQuery -->
<script src="{{ asset('backend/assets/summernote/summernote-bs4.min.js') }}"></script>
<script>
    $(function() {
        // Initialize Summernote for the first editor with the "Italic" tool
        $('.summernote').summernote({
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['link', 'picture', 'video']],
                ['misc', ['codeview', 'fullscreen']]
            ],
            tabDisable: false // Enable tab key functionality
        });

        // Initialize CodeMirror for the first textarea
        CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
            mode: "htmlmixed",
            theme: "monokai"
        });
    });

    $(function() {
        // Initialize Summernote for the second editor with the "Italic" tool
        $('.summernote_two').summernote({
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['link', 'picture', 'video']],
                ['misc', ['codeview', 'fullscreen']]
            ],
            tabDisable: false // Enable tab key functionality
        });

        // Initialize CodeMirror for the second textarea
        CodeMirror.fromTextArea(document.getElementById("codeMirrorDemoTwo"), {
            mode: "htmlmixed",
            theme: "monokai"
        });
    });
</script>
@endpush

resources/views/dashboard/gallery/edit.blade.php
@extends('dashboard.layouts.app')
@push('css')
<link rel="stylesheet" href="{{ asset('backend/assets/summernote/summernote-bs4.min.css') }}">

@endpush
@section('content')
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Gallery</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Gallery</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{route('admin-gallery.update',$data->id)}}" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="card-body">

                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">Full Title</label>
                                <div class="col-md-3">
                                    <input class="form-control" name="title" type="text" value="{{$data->title}}" id="example-text-input">
                                </div>
                                <label for="example-search-input" class="col-md-2 col-form-label">पुरा शीर्षक</label>
                                <div class="col-md-3">
                                    <input class="form-control" name="title_np" type="text" value="{{$data->title_np}}" id="nepali">
                                </div>
                            </div>

                            <div class="mb-3 row">
                                <label for="example-email-input" class="col-md-2 col-form-label">Description</label>
                                <div class="col-md-12">
                                    <textarea class="summernote form-control" name="description" id="description">{!!$data->description!!}</textarea>
                                </div>
                                <label for="example-email-input" class="col-md-2 col-form-label">विवरण</label>
                                <div class="col-md-12">
                                    <textarea class="summernote_two form-control" name="description_np" id="description_np">{!!$data->description_np!!}</textarea>
                                </div>
                            </div>

                            <div class="mb-3 row">
                                <label for="example-email-input" class="col-md-2 col-form-label">File</label>
                                <div class="col-md-3">
                                    <input class="form-control" name="image[]" type="file" value="" placeholder="" id="galleryimages" multiple> <br>
                                    <div id="previews"></div>
                                </div>

                                @if(isset($data))
                                @if(count($data->galleryimages) > 0)
                                <label for="current-image">Current Images</label>
                                <div class="row">
                                    @foreach($data->galleryimages as $galleryimage)
                                    <div class="col-md-3 col-sm-4 col-lx-3">
                                        <img src="{{asset($galleryimage->image) }}" style="height: 60px; width:60px;" alt="{{$data->title}}"><br>
                                        <a href="{{route('admin.galleryimage.remove', ['galleryimage'=>$galleryimage->id])}}">Remove</a>
                                    </div>
                                    @endforeach
                                </div>
                                @else
                                <p class="text-center">No images available.</p>
                                @endif
                                @endif

                            </div>


                        </div>

                        <div class="card-body">
                            <div class="col-sm-6">
                                <div class="mt-4">
                                    <div>
                                        <div class="input-group">
                                            <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </form>
                </div>
            </div> <!-- end col -->
        </div>
        <!-- end row -->

    </div> <!-- container-fluid -->
</div>
<!-- End Page-content -->
@endsection
@push('js')
<script src="https://unpkg.com/nepalify"></script>
<script>
    nepalify.interceptElementById("nepali");
</script>
<!-- jQuery -->
<script src="{{ asset('backend/assets/summernote/summernote-bs4.min.js') }}"></script>
<script>
    $(function() {
        // Initialize Summernote for the first editor with the "Italic" tool
        $('.summernote').summernote({
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['link', 'picture', 'video']],
                ['misc', ['codeview', 'fullscreen']]
            ],
            tabDisable: false // Enable tab key functionality
        });

        // Initialize CodeMirror for the first textarea
        CodeMirror.fromTextArea(document.getElementById("codeMirrorDemo"), {
            mode: "htmlmixed",
            theme: "monokai"
        });
    });

    $(function() {
        // Initialize Summernote for the second editor with the "Italic" tool
        $('.summernote_two').summernote({
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['insert', ['link', 'picture', 'video']],
                ['misc', ['codeview', 'fullscreen']]
            ],
            tabDisable: false // Enable tab key functionality
        });

        // Initialize CodeMirror for the second textarea
        CodeMirror.fromTextArea(document.getElementById("codeMirrorDemoTwo"), {
            mode: "htmlmixed",
            theme: "monokai"
        });
    });
</script>
<script>
    $("#galleryimages").change(function(e) {
        var files = e.originalEvent.srcElement.files;
        var imgPreview = document.getElementById('previews');
        if (files) {
            $('#previews').html("");
            var fileslength = files.length;
            for (i = 0; i < fileslength; i++) {
                if (files[i].type == 'image/png' || files[i].type == 'image/jpg' || files[i].type == 'image/jpeg') {
                    var reader = new FileReader();
                    reader.onload = function(event) {
                        $($.parseHTML("<img class='pic' style='height: 90px; width:90px;'>"))
                            .attr('src', event.target.result).appendTo(imgPreview);
                    }
                    reader.readAsDataURL(files[i]);
                }
            }
        }
    });
</script>
@endpush