routes/backend.php
<?php

use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\BannernoticeController;
use App\Http\Controllers\Backend\CareercategoryController;
use App\Http\Controllers\Backend\CareerController;
use App\Http\Controllers\Backend\CareerpositionController;
use App\Http\Controllers\Backend\Contact\ContactedController;
use App\Http\Controllers\Backend\Contact\ReportinformationController;
use App\Http\Controllers\Backend\ContactusController;
use App\Http\Controllers\Backend\DepartmentController;
use App\Http\Controllers\Backend\DesignationController;
use App\Http\Controllers\Backend\GalleryController;
use App\Http\Controllers\Backend\ImportantlinkController;
use App\Http\Controllers\Backend\NewsController;
use App\Http\Controllers\Backend\NoticecategoryController;
use App\Http\Controllers\Backend\NoticeController;
use App\Http\Controllers\Backend\PopupnoticeController;
use App\Http\Controllers\Backend\RegulationcategoryController;
use App\Http\Controllers\Backend\RegulationController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingdepartmentController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingroleController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingstaffController;
use App\Http\Controllers\Backend\StaffController;
use App\Http\Controllers\Backend\TendercategoryController;
use App\Http\Controllers\Backend\TenderController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['middleware' => 'admin'], function () {
    Route::get('dashboard', function () {
        return view('dashboard.index');
    })->name('dashboard.index');
    Route::resource('admin-banner-notice', BannernoticeController::class);
    Route::resource('admin-banner', BannerController::class);
    Route::resource('admin-notice-category', NoticecategoryController::class);
    Route::resource('admin-notice', NoticeController::class);
    Route::resource('admin-news', NewsController::class);
    Route::resource('admin-tender-category', TendercategoryController::class);
    Route::resource('admin-tender', TenderController::class);
    Route::resource('admin-career-category', CareercategoryController::class);
    Route::resource('admin-career-position', CareerpositionController::class);
    Route::resource('admin-career', CareerController::class);
    Route::resource('admin-designation', DesignationController::class);
    Route::resource('admin-department', DepartmentController::class);
    Route::resource('admin-staff', StaffController::class);
    Route::resource('admin-gallery', GalleryController::class);
    Route::get('admin/galleries/image/remove/{galleryimage}', 'App\Http\Controllers\Backend\GalleryController@removeGalleryImage')->name('admin.galleryimage.remove');

    Route::resource('admin-important-link', ImportantlinkController::class);
    Route::resource('admin-contact-detail', ContactusController::class);
    Route::resource('admin-trainer', TrainingstaffController::class);
    Route::resource('admin-training-role', TrainingroleController::class);
    Route::resource('admin-training-department', TrainingdepartmentController::class);
    Route::resource('admin-regulation-category', RegulationcategoryController::class);
    Route::resource('admin-regulation', RegulationController::class);

    Route::resource('admin-pop-notice', PopupnoticeController::class);

    Route::resource('admin-contacted', ContactedController::class);
    Route::resource('admin-report-information', ReportinformationController::class);

    Route::get('settings', 'App\Http\Controllers\Backend\Configuration\ConfigurationController@getConfiguration')->name('settings');
    Route::post('settings', 'App\Http\Controllers\Backend\Configuration\ConfigurationController@postConfiguration')->name('settings.update');
    Route::get('admin-about-us', 'App\Http\Controllers\Backend\Configuration\AboutusController@getConfiguration')->name('admin-about-us');
    Route::post('admin-about-us', 'App\Http\Controllers\Backend\Configuration\AboutusController@postConfiguration')->name('admin-about-us.update');
});

Route::get('/admin/login', 'App\Http\Controllers\Admin\Auth\AdminloginController@adminLogin')->name('admin/login');
Route::post('/loginadmin', 'App\Http\Controllers\Admin\Auth\AdminloginController@postAdminLogin')->name('loginadmin');
Route::get('/adminlogout', 'App\Http\Controllers\Admin\Auth\AdminloginController@adminLogout')->name('adminlogout');

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', 'App\Http\Controllers\Frontend\Home\HomeController@index')->name('/');
Route::get('about-us', 'App\Http\Controllers\Frontend\AboutUs\AboutusController@index')->name('about-us');
Route::get('tender', 'App\Http\Controllers\Frontend\Tender\TenderController@index')->name('tender');
Route::get('career', 'App\Http\Controllers\Frontend\Career\CareerController@index')->name('career');
Route::get('notice', 'App\Http\Controllers\Frontend\Notice\NoticeController@index')->name('notice');
Route::get('contact-us', 'App\Http\Controllers\Frontend\ContactUs\ContactusController@index')->name('contact-us');

Route::post('contact-us/post', 'App\Http\Controllers\Frontend\ContactUs\ContactusController@postIndex')->name('contact-us.post');

Route::get('gallery', 'App\Http\Controllers\Frontend\Gallery\GalleryController@index')->name('gallery');

Route::get('report-information', 'App\Http\Controllers\Frontend\ReportInformation\ReportInformationController@index')->name('report-information');
Route::post('report-information/post', 'App\Http\Controllers\Frontend\ReportInformation\ReportInformationController@postIndex')->name('report-information.post');

Route::get('regulation', 'App\Http\Controllers\Frontend\Regulation\RegulationController@index')->name('regulation');
Route::get('news-detail/{slug}', 'App\Http\Controllers\Frontend\Home\HomeController@getNewsdetail')->name('news-detail');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Training/Material/TrainingMaterial.php
<?php

namespace App\Models\Training\Material;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TrainingMaterial extends Model
{
    use HasFactory;
    protected $fillable=['title','title_np','description','description_np','image','slug','type','status','department_id'];
}

app/Http/Controllers/Training/Dashboard/Home/HomeController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Home;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        return view('Training.dashboard.index');
    }
}

app/Http/Controllers/Training/Dashboard/Material/MaterialController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Material;

use App\Http\Controllers\Controller;
use App\Models\Training\Material\TrainingMaterial;
use App\Models\RolesAndPermission\TrainingDepartment;
use Illuminate\Http\Request;
use App\Services\GenericService;
use Yajra\DataTables\DataTables;

class MaterialController extends Controller
{
    protected $genericService;

    public function __construct(GenericService $genericService)
    {
        $this->genericService = $genericService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = TrainingMaterial::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    $actionBtn = '<a title="Edit About-Us" href="/training-material/' . $data->id . '/edit" class="btn btn-sm btn-primary mr-2"><i class="fas fa-edit"></i></a>';
                    $actionBtn .= '<a title="Delete About-Us" class="btn btn-sm btn-danger" onclick="handleDelete(' . $data->id . ')"><i class="fas fa-trash"></i></a>';
                    return $actionBtn;
                })
                ->addColumn('status', function ($data) {
                    return $data->status == '0' ? 'In-Active' : 'Active';
                })
                ->addColumn('image', function ($data) {
                    $imagePath = $data->image ? asset('Admin/files/TrainingMaterial/'.$data->image) : asset('default_image/profile.png');
                    return '<a href="'.$imagePath.'" width="50" height="50" target="__blank" />View</a>';
                })
                ->rawColumns(['action','image'])
                ->make(true);
        }
        return view('Training.Dashboard.material.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $category=TrainingDepartment::all();
        return view('Training.Dashboard.material.create',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $this->genericService->store(new TrainingMaterial, $request->only(['title','title_np','description','description_np','slug','status','category_id','type']), $request->file('image'), 'image', 'slug','type');
        toast('Data Stored!', 'success');
        return redirect()->route('training-material.index')->with('success', 'Data created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = TrainingMaterial::findOrFail($id);
        $category=TrainingDepartment::all();
        return view('Training.Dashboard.material.edit', compact('data','category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $result = $this->genericService->update(new TrainingMaterial, $request->only(['title','title_np','description','description_np','slug','status','category_id','type']), $id, $request->file('image'), 'image', 'title', 'Admin/files/Notice');

        if ($result) {
            toast('Data Updated!', 'success');
            return redirect()->route('training-material.index')->with('success', 'Data updated successfully.');
        } else {
            return redirect()->route('training-material.index')->with('error', 'Failed to update testimonial.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = TrainingMaterial::find($id);
        if (file_exists('Admin/files/TrainingMaterial/' . basename($data->image))) {
            unlink('Admin/files/TrainingMaterial/' . basename($data->image));
        }
        $data->delete();
        // Alert::success('Congrats', 'You\'ve Successfully Deleted Data');
        toast('Data Deleted!', 'success');
        return redirect()->route('training-material.index');
    }
}

app/Http/Controllers/Training/Dashboard/Trainee/TraineeController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Trainee;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Training\TrainingStaff;
use App\Models\RolesAndPermission\TrainingRole;
use App\Models\RolesAndPermission\TrainingDepartment;
use App\Services\GenericService;
use Yajra\DataTables\DataTables;
use Illuminate\Support\Facades\Hash;

class TraineeController extends Controller
{
    protected $genericService;

    public function __construct(GenericService $genericService)
    {
        $this->genericService = $genericService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = TrainingStaff::latest()->where('role_id', 2)->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    $actionBtn = '<a title="Edit About-Us" href="/training-trainee/' . $data->id . '/edit" class="btn btn-sm btn-primary mr-2"><i class="fas fa-edit"></i></a>';
                    $actionBtn .= '<a title="Delete About-Us" class="btn btn-sm btn-danger" onclick="handleDelete(' . $data->id . ')"><i class="fas fa-trash"></i></a>';
                    return $actionBtn;
                })
                ->addColumn('status', function ($data) {
                    return $data->status == '0' ? 'In-Active' : 'Active';
                })
                ->addColumn('image', function ($data) {
                    $imagePath = $data->image ? asset('Admin/files/TrainingStaff/' . $data->image) : asset('default_image/profile.png');
                    return '<img src="' . $imagePath . '" width="50" height="50" />';
                })
                ->rawColumns(['action', 'image'])
                ->make(true);
        }
        return view('Training.dashboard.trainee.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $role = TrainingRole::where('id', 2)->get();
        $department = TrainingDepartment::all();
        return view('Training.dashboard.trainee.create', compact('role', 'department'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'name_np' => 'required',
            'password' => 'required', // Add validation rule for password
        ]);

        $data = $request->only(['name', 'name_np', 'email', 'image', 'slug', 'status', 'role_id','expiry_date']);
        $data['password'] = bcrypt($request->password); // Hash the password

        $this->genericService->store(new TrainingStaff, $data, $request->file('image'), 'image', 'slug');
        toast('Data Stored!', 'success');
        return redirect()->route('training-trainee.index')->with('success', 'Data created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = TrainingStaff::findOrFail($id);
        $department = TrainingDepartment::all();
        return view('Training.dashboard.trainee.edit', compact('data', 'department'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'name_np' => 'required',
        ]);

        $data = $request->only(['name', 'name_np', 'email', 'password', 'image', 'slug', 'status', 'role_id','expiry_date']);

        if (!empty($data['password'])) {
            $data['password'] = bcrypt($data['password']);
        } else {
            unset($data['password']);
        }

        $result = $this->genericService->update(new TrainingStaff, $data, $id, $request->file('image'), 'image', 'slug', 'Admin/files/TrainingStaff');

        if ($result) {
            toast('Data Updated!', 'success');
            return redirect()->route('training-trainee.index')->with('success', 'Data updated successfully.');
        } else {
            return redirect()->route('training-trainee.index')->with('error', 'Failed to update testimonial.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = TrainingStaff::find($id);
        if (file_exists('Admin/files/TrainingStaff/' . basename($data->image))) {
            unlink('Admin/files/TrainingStaff/' . basename($data->image));
        }
        $data->delete();
        // Alert::success('Congrats', 'You\'ve Successfully Deleted Data');
        toast('Data Deleted!', 'success');
        return redirect()->route('training-trainee.index');
    }
}

resources/views/dashboard/training/role/create.blade.php
@extends('dashboard.layouts.app')

@section('content')
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Training Role</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Training Role</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{ route('admin-training-role.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">
                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">Training Role</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="name" type="text" placeholder="Notice" id="example-text-input">
                                </div>
                                <label for="example-search-input" class="col-md-2 col-form-label">टेन्डर वर्ग</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="name_np" type="text" placeholder="सूचना" id="nepali">
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="col-sm-6">
                                <div class="mt-4">
                                    <div>
                                        <div class="input-group">
                                            <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div> <!-- container-fluid -->
</div> <!-- End Page-content -->
@endsection
@push('js')
<script src="https://unpkg.com/nepalify"></script>
<script>
    nepalify.interceptElementById("nepali");
</script>
@endpush

resources/views/dashboard/training/role/edit.blade.php
@extends('dashboard.layouts.app')

@section('content')
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">TRaining Role</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">TRaining Role</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{route('admin-training-role.update',$data->id)}}" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="card-body">
                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">Designation</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="name" type="text" value="{{$data->name}}" placeholder="Notice" id="example-text-input">
                                </div>
                                <label for="example-search-input" class="col-md-2 col-form-label">टेन्डर वर्ग</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="name_np" type="text" value="{{$data->name_np}}" placeholder="सूचना" id="nepali">
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="col-sm-6">
                                <div class="mt-4">
                                    <div>
                                        <div class="input-group">
                                            <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div> <!-- container-fluid -->
</div> <!-- End Page-content -->
@endsection
@push('js')
<script src="https://unpkg.com/nepalify"></script>
<script>
    nepalify.interceptElementById("nepali");
</script>
@endpush

resources/views/dashboard/training/role/index.blade.php
@extends('dashboard.layouts.app')
@push('css')
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header mt-5">
                    <h3 class="card-title">Training Role</h3>
                    <!-- <span>
                        <a href="{{ route('admin-training-role.create') }}" class="btn btn-sm btn-success float-right">Add New</a>
                    </span> -->
                </div>
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped yajra-datatable">
                        <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>Full Notice</th>
                                <th>पुरा सूचना</th>
                                <th>Status</th>
                                <th width="150px">Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <form method="POST" id="deleteGalleryForm" action="">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Confirmation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="text-center text-bold">Are you sure you want to delete this?</p>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go Back</button>
                    <button type="submit" class="btn btn-danger">Yes, Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('js')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(function() {
        var table = $('.yajra-datatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('admin-training-role.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'name', name: 'name'},
                {data: 'name_np', name: 'name_np'},
                {data: 'status', name: 'status'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });
    });

    function handleDelete(id) {
        var form = document.getElementById('deleteGalleryForm');
        form.action = 'admin-training-role/' + id;
        $('#confirmDeleteModal').modal('show');
    }
</script>
@endpush