routes/backend.php
<?php

use App\Http\Controllers\Backend\BannerController;
use App\Http\Controllers\Backend\BannernoticeController;
use App\Http\Controllers\Backend\CareercategoryController;
use App\Http\Controllers\Backend\CareerController;
use App\Http\Controllers\Backend\CareerpositionController;
use App\Http\Controllers\Backend\Contact\ContactedController;
use App\Http\Controllers\Backend\Contact\ReportinformationController;
use App\Http\Controllers\Backend\ContactusController;
use App\Http\Controllers\Backend\DepartmentController;
use App\Http\Controllers\Backend\DesignationController;
use App\Http\Controllers\Backend\GalleryController;
use App\Http\Controllers\Backend\ImportantlinkController;
use App\Http\Controllers\Backend\NewsController;
use App\Http\Controllers\Backend\NoticecategoryController;
use App\Http\Controllers\Backend\NoticeController;
use App\Http\Controllers\Backend\PopupnoticeController;
use App\Http\Controllers\Backend\RegulationcategoryController;
use App\Http\Controllers\Backend\RegulationController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingdepartmentController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingroleController;
use App\Http\Controllers\Backend\RolesAndPermission\TrainingstaffController;
use App\Http\Controllers\Backend\StaffController;
use App\Http\Controllers\Backend\TendercategoryController;
use App\Http\Controllers\Backend\TenderController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::group(['middleware' => 'admin'], function () {
    Route::get('dashboard', function () {
        return view('dashboard.index');
    })->name('dashboard.index');
    Route::resource('admin-banner-notice', BannernoticeController::class);
    Route::resource('admin-banner', BannerController::class);
    Route::resource('admin-notice-category', NoticecategoryController::class);
    Route::resource('admin-notice', NoticeController::class);
    Route::resource('admin-news', NewsController::class);
    Route::resource('admin-tender-category', TendercategoryController::class);
    Route::resource('admin-tender', TenderController::class);
    Route::resource('admin-career-category', CareercategoryController::class);
    Route::resource('admin-career-position', CareerpositionController::class);
    Route::resource('admin-career', CareerController::class);
    Route::resource('admin-designation', DesignationController::class);
    Route::resource('admin-department', DepartmentController::class);
    Route::resource('admin-staff', StaffController::class);
    Route::resource('admin-gallery', GalleryController::class);
    Route::get('admin/galleries/image/remove/{galleryimage}', 'App\Http\Controllers\Backend\GalleryController@removeGalleryImage')->name('admin.galleryimage.remove');

    Route::resource('admin-important-link', ImportantlinkController::class);
    Route::resource('admin-contact-detail', ContactusController::class);
    Route::resource('admin-trainer', TrainingstaffController::class);
    Route::resource('admin-training-role', TrainingroleController::class);
    Route::resource('admin-training-department', TrainingdepartmentController::class);
    Route::resource('admin-regulation-category', RegulationcategoryController::class);
    Route::resource('admin-regulation', RegulationController::class);

    Route::resource('admin-pop-notice', PopupnoticeController::class);

    Route::resource('admin-contacted', ContactedController::class);
    Route::resource('admin-report-information', ReportinformationController::class);

    Route::get('settings', 'App\Http\Controllers\Backend\Configuration\ConfigurationController@getConfiguration')->name('settings');
    Route::post('settings', 'App\Http\Controllers\Backend\Configuration\ConfigurationController@postConfiguration')->name('settings.update');
    Route::get('admin-about-us', 'App\Http\Controllers\Backend\Configuration\AboutusController@getConfiguration')->name('admin-about-us');
    Route::post('admin-about-us', 'App\Http\Controllers\Backend\Configuration\AboutusController@postConfiguration')->name('admin-about-us.update');
});

Route::get('/admin/login', 'App\Http\Controllers\Admin\Auth\AdminloginController@adminLogin')->name('admin/login');
Route::post('/loginadmin', 'App\Http\Controllers\Admin\Auth\AdminloginController@postAdminLogin')->name('loginadmin');
Route::get('/adminlogout', 'App\Http\Controllers\Admin\Auth\AdminloginController@adminLogout')->name('adminlogout');

routes/frontend.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', 'App\Http\Controllers\Frontend\Home\HomeController@index')->name('/');
Route::get('about-us', 'App\Http\Controllers\Frontend\AboutUs\AboutusController@index')->name('about-us');
Route::get('tender', 'App\Http\Controllers\Frontend\Tender\TenderController@index')->name('tender');
Route::get('career', 'App\Http\Controllers\Frontend\Career\CareerController@index')->name('career');
Route::get('notice', 'App\Http\Controllers\Frontend\Notice\NoticeController@index')->name('notice');
Route::get('contact-us', 'App\Http\Controllers\Frontend\ContactUs\ContactusController@index')->name('contact-us');

Route::post('contact-us/post', 'App\Http\Controllers\Frontend\ContactUs\ContactusController@postIndex')->name('contact-us.post');

Route::get('gallery', 'App\Http\Controllers\Frontend\Gallery\GalleryController@index')->name('gallery');

Route::get('report-information', 'App\Http\Controllers\Frontend\ReportInformation\ReportInformationController@index')->name('report-information');
Route::post('report-information/post', 'App\Http\Controllers\Frontend\ReportInformation\ReportInformationController@postIndex')->name('report-information.post');

Route::get('regulation', 'App\Http\Controllers\Frontend\Regulation\RegulationController@index')->name('regulation');
Route::get('news-detail/{slug}', 'App\Http\Controllers\Frontend\Home\HomeController@getNewsdetail')->name('news-detail');

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/ImportantLink/ImportantLink.php
<?php

namespace App\Models\ImportantLink;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ImportantLink extends Model
{
    use HasFactory;
    protected $fillable=['title','title_np','url','status'];
}

app/Http/Controllers/Backend/ImportantlinkController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\ImportantLink\ImportantLink;
use Illuminate\Http\Request;
use App\Services\GenericService;
use Yajra\DataTables\DataTables;

class ImportantlinkController extends Controller
{
    protected $genericService;

    public function __construct(GenericService $genericService)
    {
        $this->genericService = $genericService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = ImportantLink::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    $actionBtn = '<a title="Edit About-Us" href="/admin-important-link/' . $data->id . '/edit" class="btn btn-sm btn-primary mr-2"><i class="fas fa-edit"></i></a>';
                    $actionBtn .= '<a title="Delete About-Us" class="btn btn-sm btn-danger" onclick="handleDelete(' . $data->id . ')"><i class="fas fa-trash"></i></a>';
                    return $actionBtn;
                })
                ->addColumn('status', function ($data) {
                    return $data->status == '0' ? 'In-Active' : 'Active';
                })
                ->addColumn('image', function ($data) {
                    $imagePath = $data->url;
                    return '<a href="'.$imagePath.'" width="50" height="50" target="__blank" />View</a>';
                })
                ->rawColumns(['action'])
                ->make(true);
        }
        return view('dashboard.important_links.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('dashboard.important_links.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $this->genericService->store(new ImportantLink, $request->only(['title','title_np','url','status']));
        toast('Data Stored!', 'success');
        return redirect()->route('admin-important-link.index')->with('success', 'Data created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = ImportantLink::findOrFail($id);
        return view('dashboard.important_links.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $result = $this->genericService->update(new ImportantLink, $request->only(['title','title_np','url','status']), $id);

        if ($result) {
            toast('Data Updated!', 'success');
            return redirect()->route('admin-important-link.index')->with('success', 'Data updated successfully.');
        } else {
            return redirect()->route('admin-important-link.index')->with('error', 'Failed to update testimonial.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = ImportantLink::find($id);
        $data->delete();
        toast('Data Deleted!', 'success');
        // Alert::success('Congrats', 'You\'ve Successfully Deleted Data');
        return redirect()->route('admin-important-link.index');
    }
}

app/Http/Controllers/Training/Dashboard/Home/HomeController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Home;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(){
        return view('Training.dashboard.index');
    }
}

app/Http/Controllers/Training/Dashboard/Material/MaterialController.php
<?php

namespace App\Http\Controllers\Training\Dashboard\Material;

use App\Http\Controllers\Controller;
use App\Models\Training\Material\TrainingMaterial;
use App\Models\RolesAndPermission\TrainingDepartment;
use Illuminate\Http\Request;
use App\Services\GenericService;
use Yajra\DataTables\DataTables;

class MaterialController extends Controller
{
    protected $genericService;

    public function __construct(GenericService $genericService)
    {
        $this->genericService = $genericService;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = TrainingMaterial::latest()->get();
            return DataTables::of($data)
                ->addIndexColumn()
                ->addColumn('action', function ($data) {
                    $actionBtn = '<a title="Edit About-Us" href="/training-material/' . $data->id . '/edit" class="btn btn-sm btn-primary mr-2"><i class="fas fa-edit"></i></a>';
                    $actionBtn .= '<a title="Delete About-Us" class="btn btn-sm btn-danger" onclick="handleDelete(' . $data->id . ')"><i class="fas fa-trash"></i></a>';
                    return $actionBtn;
                })
                ->addColumn('status', function ($data) {
                    return $data->status == '0' ? 'In-Active' : 'Active';
                })
                ->addColumn('image', function ($data) {
                    $imagePath = $data->image ? asset('Admin/files/TrainingMaterial/'.$data->image) : asset('default_image/profile.png');
                    return '<a href="'.$imagePath.'" width="50" height="50" target="__blank" />View</a>';
                })
                ->rawColumns(['action','image'])
                ->make(true);
        }
        return view('Training.Dashboard.material.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $category=TrainingDepartment::all();
        return view('Training.Dashboard.material.create',compact('category'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $this->genericService->store(new TrainingMaterial, $request->only(['title','title_np','description','description_np','slug','status','category_id','type']), $request->file('image'), 'image', 'slug','type');
        toast('Data Stored!', 'success');
        return redirect()->route('training-material.index')->with('success', 'Data created successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = TrainingMaterial::findOrFail($id);
        $category=TrainingDepartment::all();
        return view('Training.Dashboard.material.edit', compact('data','category'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'title_np' => 'required',
        ]);

        $result = $this->genericService->update(new TrainingMaterial, $request->only(['title','title_np','description','description_np','slug','status','category_id','type']), $id, $request->file('image'), 'image', 'title', 'Admin/files/Notice');

        if ($result) {
            toast('Data Updated!', 'success');
            return redirect()->route('training-material.index')->with('success', 'Data updated successfully.');
        } else {
            return redirect()->route('training-material.index')->with('error', 'Failed to update testimonial.');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = TrainingMaterial::find($id);
        if (file_exists('Admin/files/TrainingMaterial/' . basename($data->image))) {
            unlink('Admin/files/TrainingMaterial/' . basename($data->image));
        }
        $data->delete();
        // Alert::success('Congrats', 'You\'ve Successfully Deleted Data');
        toast('Data Deleted!', 'success');
        return redirect()->route('training-material.index');
    }
}

resources/views/dashboard/important_links/create.blade.php
@extends('dashboard.layouts.app')

@section('content')
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Important Links</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Important Links</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{ route('admin-important-link.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">
                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">Title</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="title" type="text" placeholder="Notice" id="example-text-input">
                                </div>
                                <label for="example-search-input" class="col-md-2 col-form-label">शीर्षक</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="title_np" type="text" placeholder="सूचना" id="nepali">
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">URL/Link</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="url" type="text" placeholder="URL/Link" id="example-text-input">
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="col-sm-6">
                                <div class="mt-4">
                                    <div>
                                        <div class="input-group">
                                            <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Submit</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div> <!-- container-fluid -->
</div> <!-- End Page-content -->
@endsection
@push('js')
<script src="https://unpkg.com/nepalify"></script>
<script>
    nepalify.interceptElementById("nepali");
</script>
@endpush

resources/views/dashboard/important_links/edit.blade.php
@extends('dashboard.layouts.app')

@section('content')
<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Important Links</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Important Links</a></li>
                            <li class="breadcrumb-item active">Create</li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- end page title -->

        <div class="row">
            <div class="col-12">
                <div class="card">
                    <form action="{{route('admin-important-link.update',$data->id)}}" method="post" enctype="multipart/form-data">
                        @method('PUT')
                        @csrf
                        <div class="card-body">
                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">Title</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="title" type="text" value="{{$data->title}}" placeholder="Notice" id="example-text-input">
                                </div>
                                <label for="example-search-input" class="col-md-2 col-form-label">शीर्षक</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="title_np" type="text" value="{{$data->title_np}}" placeholder="सूचना" id="nepali">
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="mb-3 row">
                                <label for="example-text-input" class="col-md-2 col-form-label">URL/Link</label>
                                <div class="col-md-12">
                                    <input class="form-control" name="url" type="text" value="{{$data->url}}" placeholder="Notice" id="example-text-input">
                                </div>
                            </div>
                        </div>
                        <div class="card-body">
                            <div class="col-sm-6">
                                <div class="mt-4">
                                    <div>
                                        <div class="input-group">
                                            <button class="btn btn-primary" type="submit" id="inputGroupFileAddon04">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div> <!-- end col -->
        </div> <!-- end row -->
    </div> <!-- container-fluid -->
</div> <!-- End Page-content -->
@endsection
@push('js')
<script src="https://unpkg.com/nepalify"></script>
<script>
    nepalify.interceptElementById("nepali");
</script>
@endpush

resources/views/dashboard/important_links/index.blade.php
@extends('dashboard.layouts.app')
@push('css')
<link href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css" rel="stylesheet">
@endpush

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header mt-5">
                    <h3 class="card-title">Important Links</h3>
                    <span>
                        <a href="{{ route('admin-important-link.create') }}" class="btn btn-sm btn-success float-right">Add New</a>
                    </span>
                </div>
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped yajra-datatable">
                        <thead>
                            <tr>
                                <th>S.N.</th>
                                <th>Full Title</th>
                                <th>पुरा शीर्षक</th>
                                <th>URL/Link</th>
                                <th>Status</th>
                                <th width="150px">Action</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmDeleteModal">
    <div class="modal-dialog">
        <form method="POST" id="deleteGalleryForm" action="">
            @csrf
            @method('DELETE')
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Delete Confirmation</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p class="text-center text-bold">Are you sure you want to delete this?</p>
                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">No, Go Back</button>
                    <button type="submit" class="btn btn-danger">Yes, Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection

@push('js')
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
    $(function() {
        var table = $('.yajra-datatable').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('admin-important-link.index') }}",
            columns: [
                {data: 'DT_RowIndex', name: 'DT_RowIndex'},
                {data: 'title', name: 'title'},
                {data: 'title_np', name: 'title_np'},
                {data: 'url', name: 'url'},
                {data: 'status', name: 'status'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
            ]
        });
    });

    function handleDelete(id) {
        var form = document.getElementById('deleteGalleryForm');
        form.action = 'admin-important-link/' + id;
        $('#confirmDeleteModal').modal('show');
    }
</script>
@endpush